### PR TITLE
test: touched vs. touche

### LINKED ISSUE #1: "touchéd" is not the correct form of "touched"
The word "touchéd" is not a real word.  It isn't the correct form of "touched".

> Incorrect usage of the word: “touched”, use “touchéd” instead  diacritics

### PR DESCRIPTION
**Pull request by docwhat**
Some words shouldn't allow suffixes.

Fixes #1

### CODE REVIEW

**Comment by docwhat** [comment]
@sapegin I wrote the tests to check this, but I can't figure out how to fix it just for `touché` and not break things like `dopplegänger` and its plural.

I suppose I could remove the `[\w-]s` check and the suffixes test and then manually add plurals to the word list?

**Comment by sapegin** [comment]
> I suppose I could remove the [\w-]s check and the suffixes test and then manually add plurals to the word list?

Yeah, I think that would be the best approach.

Thanks for the PR!

**Comment by sapegin** [comment]
Thanks, merging! Sorry for the delay.

**Pull request merged**
